#
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: my_notebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
        - "5432"
    networks:
      - django-postgres
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PGUSER:postgres
      - PASSWORD:postgres
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - django-postgres
volumes:
  postgres_data:

networks:
  django-postgres:
    external: true
